
services:
  web:
    build: 
      context: . 
      dockerfile: Dockerfile.prod
    container_name: creaive.prod
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    extra_hosts:
      - "host.docker.internal:host-gateway"