# docker-compose.deploy.yml

services:
  web:
    image: creaive/creaive:latest
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    extra_hosts:
      - "host.docker.internal:host-gateway"
