
services:
  web:
    build: 
      context: . 
      dockerfile: Dockerfile.dev
    container_name: creaive.dev
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # depends_on:
    #   - mongo

  # mongo:
  #   image: mongo:6.0
  #   container_name: creaive-mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #     MONGO_INITDB_DATABASE: creaive
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db 

# volumes:
#   mongo_data:
